FROM node:14-alpine

WORKDIR /app

COPY package*.json .

RUN npm ci

COPY . .

RUN npm run build

ARG TOKEN
ENV TOKEN $TOKEN
ARG API_KEY
ENV API_KEY $API_KEY
ARG AUTH_DOMAIN
ENV AUTH_DOMAIN $AUTH_DOMAIN
ARG DB_URL
ENV DB_URL $DB_URL
ARG PROJECT_ID
ENV PROJECT_ID $PROJECT_ID
ARG STORAGE_BUCKET
ENV STORAGE_BUCKET $STORAGE_BUCKET
ARG MESSAGING_SENDER_ID
ENV MESSAGING_SENDER_ID $MESSAGING_
ARG APP_ID
ENV APP_ID $APP_ID
ARG MEASUREMENT_ID
ENV MEASUREMENT_ID $MEASUREMENT_ID

ENTRYPOINT [ "npm", "start" ]
