version: "3.7"

services:
  bot:
    image: judah-bot:latest
    container_name: judah-bot
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TOKEN=${TOKEN}
        - API_KEY=${API_KEY}
        - AUTH_DOMAIN=${AUTH_DOMAIN}
        - DB_URL=${DB_URL}
        - PROJECT_ID=${PROJECT_ID}
        - STORAGE_BUCKET=${STORAGE_BUCKET}
        - MESSAGING_SENDER_ID=${MESSAGING_SENDER_ID}
        - APP_ID=${APP_ID}
        - MEASUREMENT_ID=${MEASUREMENT_ID}
    command: npm start
