---

- name: Restart a container
  docker_container:
    name: "{{ container_name }}"
    image: "{{ image_name }}"
    state: started
    restart: yes
    env:
      TOKEN: "{{ token }}"
      API_KEY: "{{ api_key }}"
      AUTH_DOMAIN: "{{ auth_domain }}"
      DB_URL: "{{ db_url }}"
      PROJECT_ID: "{{ project_id }}"
      STORAGE_BUCKET: "{{ storage_bucket }}"
      MESSAGING_SENDER_ID: "{{ messaging_sender_id }}"
      APP_ID: "{{ app_id }}"
      MEASUREMENT_ID: "{{ measurment_id }}"

