---
name: deploy

on:
  workflow_run:
    workflows: ["push"]
    branches: [main]
    types: 
      - completed

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: deploy.yml
          directory: ./ci/ansible
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          inventory: |
            [bot-server]
            ${{ secrets.HOST }}
          options: |
            --extra-vars "token=${{ secrets.TOKEN }} api_key=${{ secrets.API_KEY }} auth_domain=${{ secrets.AUTH_DOMAIN }} db_url=${{ secrets.DB_URL }} project_id=${{ secrets.PROJECT_ID }} storage_bucket=${{ secrets.STORAGE_BUCKET }} messaging_sender_id=${{ secrets.MESSAGING_SENDER_ID }} app_id=${{ secrets.APP_ID }} measurment_id=${{ secrets.MEASURMENT_ID }}"
...
