---
name: push

on:
  workflow_run:
    workflows: ["test"]
    branches: [main]
    types: 
      - completed

env:
  CONTAINER_NAME: docker.pkg.github.com/${{ github.actor }}/${{ github.event.repository.name }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_CONNET }}

      - name: Build container
        run: docker-compose build

      - name: Push container
        run: docker push docker.pkg.github.com/gelugu/judah-bot:latest
...
