---
name: push

on:
  push:
    branches: [ main ]
  workflow_run:
    workflows: ["tests"]
    branches: [main]
    types: 
      - completed

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container
        run: docker build . -t ghcr.io/${{ github.actor }}/judah-bot:$(cat package.json | jq ".version" | tr -d "\"")

      - name: Push container
        run: docker push ghcr.io/${{ github.actor }}/judah-bot:$(cat package.json | jq ".version" | tr -d "\"")
...
